name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'shawngithubactions' 
          # Container registry password
          password: '78k9fCffRlw+4ADXCVHEHi+L7SHfCSb5tJlXBULCIG+ACRAcaqBb' 
          # Container registry server url
          login-server: 'shawngithubactions.azurecr.io'
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: shawngithubactions.azurecr.io/hello-world-app:${{ github.sha }}
          file: ./Dockerfile

  deployToAKS:
    permissions:
      actions: read
      contents: read
      id-token: write
  
    runs-on: ubuntu-latest
    needs: [buildImage]
    environment: Production
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
  
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: 'b30bd177-00f6-4bdd-87a4-19922d6a9e13'
          tenant-id: '4f289dd8-16ec-43aa-bfb6-d697943e83dc'
          subscription-id: '814b04d5-d91c-45d4-b122-3c5e24647554'

      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 'github-actions-rg'
          # AKS Cluster Name
          cluster-name: 'shawngithubactions'
          # AKS Cluster Subscription
          subscription: '814b04d5-d91c-45d4-b122-3c5e24647554'
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
          
      # Substitute environment variables in a file
      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.1.0
        env:
          MONGODB_URI: 'mongodb://shawngithubactions:LM0kbHvoXfm4f7p0v42x97iPBSRI9iQe47GZsH7Q6YIgQoQ0PA0xS0kmnsJV7blGRgIdtg6HbWnIACDb0ENwxQ==@shawngithubactions.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@shawngithubactions@'
          CONTAINER_NAME: hello-world-app:${{ github.sha }}
          AZURE_CONTAINER_REGISTRY: shawngithubactions.azurecr.io
        with:
          # File to run substitutions on
          input: 
            kubernetes/hello-world-deployment.yaml
          # File to write result to
          output: 
            hello-world-deployment.yaml          
            
      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            shawngithubactions.azurecr.io/hello-world-app:${{ github.sha }}
